import assert from 'node:assert/strict';
const base=process.env.TEST_URL||'http://127.0.0.1:5173';
const stamp=Date.now();
const password='Acceptance-'+crypto.randomUUID();
function client(){let cookie='';return async(path,method='GET',body,expected=200)=>{const r=await fetch(base+'/api/'+path,{method,headers:{...(cookie?{cookie}:{}),...(body instanceof FormData?{}:{'Content-Type':'application/json'})},...(body?{body:body instanceof FormData?body:JSON.stringify(body)}:{})});if(r.headers.get('set-cookie'))cookie=r.headers.get('set-cookie').split(';')[0];const text=await r.text();let data;try{data=JSON.parse(text)}catch{throw new Error(path+' returned non-JSON: '+text.slice(0,300))}assert.equal(r.status,expected,`${method} ${path}: ${JSON.stringify(data)}`);return data}}
const admin=client(),manager=client(),employee=client(),outsider=client(),anon=client();
await anon('state','GET',null,401);
await admin('auth/register','POST',{name:'Администратор теста',company:'Проверка '+stamp,email:`admin-${stamp}@test.local`,password,demo:true},201);
const seeded=await admin('state');assert.equal(seeded.tasks.length,8);assert.equal(seeded.users.length,5);assert.equal(seeded.rewards.length,4);
const m=await admin('users','POST',{name:'Руководитель',email:`manager-${stamp}@test.local`,password,role:'manager',department:'Продажи'},201);
const e=await admin('users','POST',{name:'Сотрудник',email:`employee-${stamp}@test.local`,password,role:'employee',department:'Продажи'},201);
await manager('auth/login','POST',{email:`manager-${stamp}@test.local`,password});
await employee('auth/login','POST',{email:`employee-${stamp}@test.local`,password});
await employee('users','POST',{name:'Нельзя',email:'forbidden@test.local',password,role:'admin'},403);
await manager('users','POST',{name:'Нельзя',email:'forbidden@test.local',password},403);
await employee('points/bonus','POST',{user_id:e.id,amount:100,reason:'Нельзя'},403);
await outsider('auth/register','POST',{name:'Другая компания',company:'Другая '+stamp,email:`other-${stamp}@test.local`,password},201);
const t=await manager('tasks','POST',{title:'Проверка цикла MVP',description:'Приложить результат, пройти доработку и получить баллы.',assignee_id:e.id,deadline:new Date(Date.now()+3600000).toISOString(),priority:'high',points:75},201);
await outsider('tasks/'+t.id,'GET',null,404);
await employee('tasks/'+seeded.tasks[0].id,'GET',null,403);
await employee('tasks/'+t.id+'/approve','POST',{},403);
await manager('tasks/'+t.id+'/approve','POST',{},409);
await employee('tasks/'+t.id+'/status','PATCH',{status:'review'},409);
await employee('tasks/'+t.id+'/status','PATCH',{status:'progress'});
await employee('tasks/'+t.id+'/comments','POST',{body:'Результат подготовлен'},201);
const upload=new FormData();upload.append('file',new File(['Результат работы'], 'result.txt',{type:'text/plain'}));await employee('tasks/'+t.id+'/attachments','POST',upload,201);
const wrong=new FormData();wrong.append('file',new File(['not a pdf'],'fake.pdf',{type:'application/pdf'}));await employee('tasks/'+t.id+'/attachments','POST',wrong,400);
await employee('tasks/'+t.id+'/status','PATCH',{status:'review'});
await manager('tasks/'+t.id+'/reject','POST',{reason:'Добавьте итоговые цифры'});
assert.equal((await employee('tasks/'+t.id)).status,'progress');
await employee('tasks/'+t.id+'/status','PATCH',{status:'review'});
const results=await Promise.all([manager('tasks/'+t.id+'/approve','POST',{}),manager('tasks/'+t.id+'/approve','POST',{}).catch(err=>{assert.match(err.message,/409/);return null})]);
const state=await employee('state');assert.equal(state.me.points,75);assert.equal(state.tasks.find(x=>x.id===t.id).status,'done');assert.equal(state.ledger.filter(x=>x.reference===`${t.id}:${e.id}`||x.reference===t.id).length,1);assert(state.notifications.some(x=>x.title.includes('Начислено 75')));assert.equal((await employee('tasks/'+t.id)).attachments.length,1);
await manager('tasks/'+t.id+'/approve','POST',{},409);
await manager('points/bonus','POST',{user_id:e.id,amount:100,reason:''},400);
await manager('points/bonus','POST',{user_id:e.id,amount:100,reason:'Помощь команде'});
const rating=await employee('rating?period=month');assert.equal(rating.find(x=>x.id===e.id).earned,175);assert.equal(rating.find(x=>x.id===e.id).completed,1);
await manager('rewards','POST',{title:'Тестовая награда',description:'Поощрение за результат',cost:150,stock:1,icon:'gift'},201);
const reward=(await employee('rewards')).find(x=>x.title==='Тестовая награда');
await employee('rewards/'+reward.id+'/claim','POST',{},201);
await employee('rewards/'+reward.id+'/claim','POST',{},409);
assert.equal((await employee('state')).me.points,175);
const claim=(await employee('state')).claims.find(x=>x.reward_id===reward.id);
await manager('claims/'+claim.id+'/approve','POST',{});
await manager('claims/'+claim.id+'/approve','POST',{},409);
const after=await employee('state');assert.equal(after.me.points,25);assert.equal(after.ledger.filter(x=>x.reference==='claim:'+claim.id).length,1);assert.equal((await employee('rating?period=all')).find(x=>x.id===e.id).earned,175);
assert(seeded.tasks.some(x=>x.overdue));assert.equal((await employee('tasks/'+t.id)).comments.length,2);
await admin('users/'+e.id,'PATCH',{active:false});await employee('state','GET',null,401);
await admin('users/'+e.id,'DELETE',{},409);
await admin('users/'+e.id,'PATCH',{active:true});await employee('auth/login','POST',{email:`employee-${stamp}@test.local`,password});
await employee('notifications','PATCH',{});assert((await employee('state')).notifications.every(x=>x.read));
await employee('auth/logout','POST',{});await employee('state','GET',null,401);
console.log('PASS: регистрация, вход, 3 роли, изоляция компаний, статусы и доработка, комментарии, файлы и проверка типов, однократное начисление при конкурентном подтверждении, бонусы, рейтинг, награды и списание, просрочки, уведомления, блокировка и выход.');
