import assert from 'node:assert/strict';
const base=process.env.TEST_URL||'http://127.0.0.1:5173', stamp=crypto.randomUUID();
const password='Test-'+crypto.randomUUID();
function client(){let cookie='';return async(path,method='GET',body,expected=200)=>{
 const r=await fetch(`${base}/api/${path}`,{method,headers:{cookie,'Content-Type':'application/json'},...(body?{body:JSON.stringify(body)}:{})});
 if(r.headers.get('set-cookie'))cookie=r.headers.get('set-cookie').split(';')[0];
 const data=await r.json();assert.equal(r.status,expected,`${method} ${path}: ${JSON.stringify(data)}`);return data;
}}
const admin=client(),a=client(),b=client(),other=client();
await admin('auth/register','POST',{name:'Тест правок',company:'Правки '+stamp,email:`admin-${stamp}@test.local`,password},201);
const ua=await admin('users','POST',{name:'Первый',email:`a-${stamp}@test.local`,password,role:'employee',department:'Маркетинг'},201);
const ub=await admin('users','POST',{name:'Второй',email:`b-${stamp}@test.local`,password,role:'employee',department:'Продажи'},201);
await a('auth/login','POST',{email:`a-${stamp}@test.local`,password});
await b('auth/login','POST',{email:`b-${stamp}@test.local`,password});
await other('auth/register','POST',{name:'Чужой',company:'Другая',email:`other-${stamp}@test.local`,password},201);
const foreign=(await other('state')).me.id;
const fields={title:'Общая работа',description:'Результат команды',deadline:new Date(Date.now()+86400000).toISOString(),priority:'normal',points:30};
const task=await admin('tasks','POST',{...fields,assignee_ids:[ua.id,ub.id,ua.id]},201);
assert.equal((await admin('tasks/'+task.id)).assignee_ids.length,2);
assert((await a('state')).tasks.some(t=>t.id===task.id));
assert((await b('state')).tasks.some(t=>t.id===task.id));
await a('tasks/'+task.id,'PATCH',{priority:'urgent'},403);
await other('tasks/'+task.id,'PATCH',{priority:'urgent'},404);
await admin('tasks/'+task.id,'PATCH',{assignee_ids:[]},400);
await admin('tasks/'+task.id,'PATCH',{assignee_ids:[foreign]},400);
await admin('tasks/'+task.id,'PATCH',{title:'Изменённая задача',priority:'urgent',points:60,assignee_ids:[ub.id]});
await a('tasks/'+task.id,'GET',null,403);
assert(!(await a('state')).tasks.some(t=>t.id===task.id));
const changed=await b('tasks/'+task.id);assert.equal(changed.priority,'urgent');assert.equal(changed.title,'Изменённая задача');assert.equal(changed.points,60);
assert(changed.activity.some(x=>x.body.includes('Изменил')));
await b('tasks/'+task.id+'/status','PATCH',{status:'progress'});
await b('tasks/'+task.id+'/status','PATCH',{status:'review'});
await admin('tasks/'+task.id,'PATCH',{assignee_ids:[ua.id,ub.id]});
assert.equal((await a('tasks/'+task.id)).status,'progress');
await a('tasks/'+task.id+'/status','PATCH',{status:'review'});
await Promise.all([admin('tasks/'+task.id+'/approve','POST',{}),admin('tasks/'+task.id+'/approve','POST',{}).catch(error=>assert.match(error.message,/409/))]);
assert.equal((await a('state')).me.points,60);assert.equal((await b('state')).me.points,60);
const ledger=(await admin('state')).ledger.filter(l=>l.reference===task.id||l.reference?.startsWith(`${task.id}:`));
assert.equal(ledger.length,2);
const rating=await admin('rating?period=all');assert.equal(rating.find(u=>u.id===ua.id).completed,1);assert.equal(rating.find(u=>u.id===ub.id).completed,1);
await admin('tasks/'+task.id,'PATCH',{points:999,priority:'low'});
assert.equal((await admin('tasks/'+task.id)).status,'done');
assert.equal((await admin('tasks/'+task.id)).priority,'low');
assert.equal((await a('state')).me.points,60);
const uc=await admin('users','POST',{name:'Третий',email:`c-${stamp}@test.local`,password,role:'employee'},201);
await admin('tasks/'+task.id,'PATCH',{assignee_ids:[ua.id,ub.id,uc.id]});
assert.equal((await admin('tasks/'+task.id)).status,'progress');
assert.equal((await admin('tasks/'+task.id)).approved_at,null);
await a('tasks/'+task.id+'/status','PATCH',{status:'review'});
await admin('tasks/'+task.id+'/approve','POST',{});
const acceptedAgain=await admin('state');
assert.equal(acceptedAgain.users.find(u=>u.id===ua.id).points,60);
assert.equal(acceptedAgain.users.find(u=>u.id===ub.id).points,60);
assert.equal(acceptedAgain.users.find(u=>u.id===uc.id).points,999);
await admin('users/'+ub.id,'DELETE',{},409);
console.log('PASS: editing active and accepted tasks, multiple assignees, reassignment access, company isolation, reopening accepted task for new assignees, per-assignee points without duplicates.');
