import { env } from 'cloudflare:workers';
import { saveTask } from './task-editor';
import { changeTaskStatus, completeTask, deleteTask } from './task-lifecycle';
type Row=Record<string,any>;
class ApiError extends Error{constructor(public status:number,message:string){super(message)}}
function fail(s:number,m:string):never{throw new ApiError(s,m)}
const now=()=>new Date().toISOString(),id=()=>crypto.randomUUID();
const db=()=>{if(!env.DB)fail(503,'База данных недоступна');return env.DB!};
const q=(sql:string,...args:any[])=>db().prepare(sql).bind(...args);
const one=async(sql:string,...a:any[])=>q(sql,...a).first<Row>();
const all=async(sql:string,...a:any[])=>(await q(sql,...a).all<Row>()).results;
const run=async(sql:string,...a:any[])=>q(sql,...a).run();
const hex=(b:ArrayBuffer)=>Array.from(new Uint8Array(b),n=>n.toString(16).padStart(2,'0')).join('');
const sha=async(s:string)=>hex(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(s)));
async function hash(p:string,s=hex(crypto.getRandomValues(new Uint8Array(16)).buffer)){const k=await crypto.subtle.importKey('raw',new TextEncoder().encode(p),'PBKDF2',false,['deriveBits']);return s+':'+hex(await crypto.subtle.deriveBits({name:'PBKDF2',hash:'SHA-256',salt:new TextEncoder().encode(s),iterations:100000},k,256))}
const safe=(u:Row)=>{const{password,...r}=u;return r};
const str=(v:any,n:string,max=5000)=>{if(typeof v!=='string'||!v.trim()||v.trim().length>max)fail(400,'Проверьте поле «'+n+'»');return v.trim()};
const num=(v:any,n:string,min=1,max=100000)=>{const x=Number(v);if(!Number.isSafeInteger(x)||x<min||x>max)fail(400,'Проверьте поле «'+n+'»');return x};
const email=(v:any)=>{const s=str(v,'Email',254).toLowerCase();if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(s))fail(400,'Некорректный email');return s};
const password=(v:any)=>{if(typeof v!=='string'||v.length<8||v.length>128)fail(400,'Пароль должен содержать от 8 до 128 символов');return v};
const manager=(u:Row)=>{if(!['admin','manager'].includes(u.role))fail(403,'Доступно только руководителю')};
const admin=(u:Row)=>{if(u.role!=='admin')fail(403,'Доступно только администратору')};
const note=(cid:string,uid:string,title:string,tid:string|null=null,nid=id())=>q('INSERT OR IGNORE INTO notifications (id,company_id,user_id,title,task_id,created_at) VALUES (?,?,?,?,?,?)',nid,cid,uid,title,tid,now());
async function managers(cid:string,title:string,tid:string|null=null){return(await all("SELECT id FROM users WHERE company_id=? AND role IN ('admin','manager') AND active=1",cid)).map(u=>note(cid,u.id,title,tid))}
async function membership(u:Row){await run('INSERT OR IGNORE INTO task_assignees (task_id,user_id) SELECT id,assignee_id FROM tasks t WHERE company_id=? AND deleted_at IS NULL AND NOT EXISTS (SELECT 1 FROM task_assignees WHERE task_id=t.id)',u.company_id)}
async function enrichTask(t:Row):Promise<Row>{const assignees=await all('SELECT u.id,u.name,u.department FROM task_assignees a JOIN users u ON u.id=a.user_id WHERE a.task_id=? ORDER BY u.name',t.id);const credited=await all('SELECT user_id FROM ledger WHERE company_id=? AND (reference=? OR reference LIKE ?)',t.company_id,t.id,t.id+':%');return {...t,points_awarded:credited.length>0,assignees,assignee_ids:assignees.map(a=>a.id),assignee_name:assignees.map(a=>a.name).join(', '),overdue:t.status!=='done'&&t.deadline<now()}}
async function taskAccess(u:Row,tid:string){const t=await one('SELECT * FROM tasks WHERE id=? AND company_id=? AND deleted_at IS NULL',tid,u.company_id);if(!t)fail(404,'Задача не найдена');const detail=await enrichTask(t!);if(u.role==='employee'&&!detail.assignee_ids.includes(u.id))fail(403,'Нет доступа к этой задаче');return detail}
async function cookie(u:Row,req:Request){const token=id()+id();await run('INSERT INTO sessions (token,user_id,expires) VALUES (?,?,?)',await sha(token),u.id,new Date(Date.now()+604800000).toISOString());return `stafftrack_session=${token}; HttpOnly; SameSite=Lax; Path=/; Max-Age=604800${new URL(req.url).protocol==='https:'?'; Secure':''}`}
async function current(req:Request){const token=req.headers.get('cookie')?.match(/(?:^|;\s*)stafftrack_session=([^;]+)/)?.[1];if(!token)fail(401,'Войдите в аккаунт');const u=await one('SELECT u.* FROM sessions s JOIN users u ON s.user_id=u.id WHERE s.token=? AND s.expires>? AND u.active=1',await sha(token!),now());if(!u)fail(401,'Сессия завершена. Войдите снова');return u!}
async function body(r:Request):Promise<Row>{try{return await r.json() as Row}catch{fail(400,'Некорректные данные запроса')}}
const jsonResponse=(data:any,status=200,h:Record<string,string>={})=>Response.json(data,{status,headers:{'Cache-Control':'no-store','X-Content-Type-Options':'nosniff',...h}});
async function sweep(u:Row){const ts=await all("SELECT * FROM tasks WHERE company_id=? AND deleted_at IS NULL AND status!='done' AND deadline<=?",u.company_id,new Date(Date.now()+86400000).toISOString());const ms=await all("SELECT id FROM users WHERE company_id=? AND role IN ('admin','manager') AND active=1",u.company_id);const inserts:any[]=[];for(const t of ts){const late=t.deadline<now();for(const uid of new Set([...(await all('SELECT user_id FROM task_assignees WHERE task_id=?',t.id)).map(a=>a.user_id),...(late?ms.map(m=>m.id):[])]))inserts.push(note(u.company_id,uid,(late?'Просрочена задача «':'Меньше суток до срока задачи «')+t.title+'»',t.id,`${late?'late':'soon'}:${t.id}:${uid}:${t.deadline}`))}if(inserts.length)await db().batch(inserts)}
async function state(u:Row){await sweep(u);const own=u.role==='employee';const[company,us,ts,ls,ns,rs,cs]=await Promise.all([
one('SELECT * FROM companies WHERE id=?',u.company_id),
all('SELECT u.id,u.name,u.email,u.phone,u.role,u.position,u.department,u.active,u.created_at,COALESCE((SELECT SUM(amount) FROM ledger WHERE user_id=u.id),0) points,COALESCE((SELECT SUM(amount) FROM ledger WHERE user_id=u.id AND amount>0),0) earned FROM users u WHERE company_id=?',u.company_id),
all('SELECT t.*,a.name assignee_name,a.department,au.name author_name FROM tasks t JOIN users a ON a.id=t.assignee_id JOIN users au ON au.id=t.author_id WHERE t.company_id=? AND t.deleted_at IS NULL'+(own?' AND EXISTS (SELECT 1 FROM task_assignees a2 WHERE a2.task_id=t.id AND a2.user_id=?)':'')+' ORDER BY t.created_at DESC',...[u.company_id,...(own?[u.id]:[])]),
all('SELECT l.*,u.name user_name,a.name approved_name FROM ledger l JOIN users u ON u.id=l.user_id JOIN users a ON a.id=l.approved_by WHERE l.company_id=?'+(own?' AND l.user_id=?':'')+' ORDER BY l.created_at DESC',...[u.company_id,...(own?[u.id]:[])]),
all('SELECT * FROM notifications WHERE user_id=? ORDER BY created_at DESC LIMIT 150',u.id),
all("SELECT r.*,r.stock-(SELECT COUNT(*) FROM claims WHERE reward_id=r.id AND status IN ('pending','confirmed')) available FROM rewards r WHERE company_id=?",u.company_id),
all('SELECT c.*,r.title,u.name user_name FROM claims c JOIN rewards r ON r.id=c.reward_id JOIN users u ON u.id=c.user_id WHERE r.company_id=?'+(own?' AND c.user_id=?':'')+' ORDER BY c.created_at DESC',...[u.company_id,...(own?[u.id]:[])])]);return{me:{...safe(u),points:us.find(x=>x.id===u.id)?.points||0},company:{...company,settings:JSON.parse(company!.settings)},users:own?us.map(({email,phone,...x})=>x):us,tasks:await Promise.all(ts.map(enrichTask)),ledger:ls,notifications:ns,rewards:rs,claims:cs}}
export async function handle(req:Request,onSession?:(cookie:string)=>void){const res=(b:any,s=200,h:Record<string,string>={})=>{if(h['Set-Cookie'])onSession?.(h['Set-Cookie']);return jsonResponse(b,s,h)};try{const url=new URL(req.url),p=url.pathname.replace(/^\/api\/?/,'').split('/').filter(Boolean),m=req.method;if(m!=='GET'){const o=req.headers.get('origin');if(o&&o!==url.origin)fail(403,'Недопустимый источник запроса')}
if(p[0]==='auth'&&p[1]==='register'&&m==='POST'){const b=await body(req),em=email(b.email),pw=await hash(password(b.password)),name=str(b.name,'Имя',120),company=str(b.company,'Компания',120),cid=id(),uid=id();if(await one('SELECT id FROM users WHERE email=?',em))fail(409,'Этот email уже зарегистрирован');const seed=[q('INSERT INTO companies (id,name,created_at) VALUES (?,?,?)',cid,company,now()),q("INSERT INTO users (id,company_id,name,email,password,role,position,created_at) VALUES (?,?,?,?,?,'admin','Администратор',?)",uid,cid,name,em,pw,now())];
if(b.demo){const names=['Анна Смирнова','Максим Волков','Елена Соколова','Дмитрий Козлов'],deps=['Маркетинг','Продажи','Маркетинг','Операции'],ids=names.map(()=>id());for(let i=0;i<4;i++)seed.push(q("INSERT INTO users (id,company_id,name,email,password,role,position,department,created_at) VALUES (?,?,?,?,?,'employee',?,?,?)",ids[i],cid,names[i],`demo-${ids[i]}@stafftrack.test`,pw,['Маркетолог','Менеджер продаж','Дизайнер','Координатор'][i],deps[i],now()));const titles=['Подготовить контент-план на октябрь','Обновить базу клиентов','Собрать макеты для новой акции','Проверить остатки на складе','Подготовить еженедельный отчёт','Оформить презентацию продукта','Связаться с новыми клиентами','Подготовить материалы для команды'];for(let i=0;i<8;i++){const tid=id(),status=['progress','new','review','progress','done','new','done','progress'][i],pts=[80,50,100,40,60,70,50,90][i];seed.push(q('INSERT INTO tasks (id,company_id,title,description,assignee_id,author_id,deadline,priority,status,points,created_at,approved_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?)',tid,cid,titles[i],'Подготовьте результат и приложите материалы к задаче. После проверки руководителем будут начислены баллы.',ids[i%4],uid,new Date(Date.now()+[2,1,0.3,-1,-2,3,-3,4][i]*86400000).toISOString(),['high','normal','high','urgent','normal','low','normal','normal'][i],status,pts,now(),status==='done'?now():null));if(status==='done')seed.push(q('INSERT INTO ledger (id,company_id,user_id,amount,reason,reference,approved_by,created_at) VALUES (?,?,?,?,?,?,?,?)',id(),cid,ids[i%4],pts,'Задача «'+titles[i]+'»',tid,uid,now()))}for(let i=0;i<4;i++)seed.push(q('INSERT INTO ledger (id,company_id,user_id,amount,reason,approved_by,created_at) VALUES (?,?,?,?,?,?,?)',id(),cid,ids[i],[320,240,180,120][i],'Бонус за инициативу',uid,now()));for(const r of [['Дополнительный выходной','Согласуйте удобную дату с руководителем.',1500,'sun'],['Подарочный сертификат','Сертификат в любимый магазин.',1000,'gift'],['Удобная смена','Выберите удобное время для работы.',700,'clock'],['Кофе за счёт компании','Небольшая награда за большую работу.',250,'coffee']])seed.push(q('INSERT INTO rewards (id,company_id,title,description,cost,stock,icon) VALUES (?,?,?,?,?,10,?)',id(),cid,...r))}await db().batch(seed);const u=(await one('SELECT * FROM users WHERE id=?',uid))!;return res({user:safe(u)},201,{'Set-Cookie':await cookie(u,req)})}
if(p[0]==='auth'&&p[1]==='login'&&m==='POST'){const b=await body(req),em=email(b.email),key=await sha(em+':'+(req.headers.get('cf-connecting-ip')||'local')),a=await one('SELECT * FROM attempts WHERE key=? AND expires>?',key,now());if(a&&a.count>=10)fail(429,'Слишком много попыток. Подождите 15 минут');const u=await one('SELECT * FROM users WHERE email=?',em),check=await hash(typeof b.password==='string'?b.password.slice(0,128):'',u?.password.split(':')[0]||'00'.repeat(16));if(!u||check!==u.password||!u.active){await run('INSERT INTO attempts (key,count,expires) VALUES (?,1,?) ON CONFLICT(key) DO UPDATE SET count=CASE WHEN expires>? THEN count+1 ELSE 1 END,expires=excluded.expires',key,new Date(Date.now()+900000).toISOString(),now());fail(401,'Неверный email или пароль')}await run('DELETE FROM attempts WHERE key=?',key);return res({user:safe(u!)},200,{'Set-Cookie':await cookie(u!,req)})}
if(p[0]==='auth'&&p[1]==='forgot'&&m==='POST'){const b=await body(req),em=email(b.email),e=env as any;if(!e.MAIL_API_URL||!e.MAIL_API_KEY)fail(503,'Отправка писем ещё не настроена. Обратитесь к администратору для смены пароля.');const u=await one('SELECT id FROM users WHERE email=? AND active=1',em);if(u){const token=id()+id();await run('INSERT INTO resets (token,user_id,expires) VALUES (?,?,?)',await sha(token),u.id,new Date(Date.now()+3600000).toISOString());const sent=await fetch(e.MAIL_API_URL,{method:'POST',headers:{Authorization:'Bearer '+e.MAIL_API_KEY,'Content-Type':'application/json'},body:JSON.stringify({from:e.MAIL_FROM,to:[em],subject:'StaffTrack — восстановление пароля',text:'Ссылка действует один час: '+url.origin+'/?reset='+token})});if(!sent.ok)fail(503,'Не удалось отправить письмо. Попробуйте позднее')}return res({message:'Если адрес зарегистрирован, письмо отправлено.'})}
if(p[0]==='auth'&&p[1]==='reset'&&m==='POST'){const b=await body(req),token=await sha(str(b.token,'Ссылка',200)),r=await one('SELECT * FROM resets WHERE token=? AND expires>?',token,now());if(!r)fail(400,'Ссылка недействительна или устарела');await db().batch([q('UPDATE users SET password=? WHERE id=? AND EXISTS (SELECT 1 FROM resets WHERE token=? AND expires>?)',await hash(password(b.password)),r!.user_id,token,now()),q('DELETE FROM resets WHERE user_id=?',r!.user_id),q('DELETE FROM sessions WHERE user_id=?',r!.user_id)]);return res({ok:true})}
const u=await current(req);await membership(u);
if(p[0]==='auth'&&p[1]==='logout'&&m==='POST'){const t=req.headers.get('cookie')!.match(/stafftrack_session=([^;]+)/)![1];await run('DELETE FROM sessions WHERE token=?',await sha(t));return res({ok:true},200,{'Set-Cookie':'stafftrack_session=; HttpOnly; SameSite=Lax; Path=/; Max-Age=0'})}
if(p[0]==='state'&&m==='GET')return res(await state(u));
if(p[0]==='rating'&&m==='GET'){const period=url.searchParams.get('period'),d=new Date();if(period==='week'){d.setUTCDate(d.getUTCDate()-((d.getUTCDay()+6)%7));d.setUTCHours(0,0,0,0)}else if(period==='month'){d.setUTCDate(1);d.setUTCHours(0,0,0,0)}else d.setUTCFullYear(1970);return res(await all("SELECT u.id,u.name,u.department,u.position,COALESCE((SELECT SUM(amount) FROM ledger WHERE user_id=u.id AND amount>0 AND created_at>=?),0) earned,(SELECT COUNT(*) FROM tasks t WHERE EXISTS (SELECT 1 FROM task_assignees a WHERE a.task_id=t.id AND a.user_id=u.id) AND status='done' AND deleted_at IS NULL AND approved_at>=?) completed FROM users u WHERE company_id=? AND role='employee' AND active=1 ORDER BY earned DESC,u.name",d.toISOString(),d.toISOString(),u.company_id))}
if(p[0]==='tasks'){if(p.length===1&&m==='GET')return res((await state(u)).tasks);if(p.length===1&&m==='POST')return res(await saveTask({q,all,db,fail,str,num,note},u,await body(req)),201);const t=await taskAccess(u,p[1]);
if(p.length===2&&m==='DELETE')return res(await deleteTask({q,all,db,fail},u,t));
if(p.length===2&&m==='PATCH')return res(await saveTask({q,all,db,fail,str,num,note},u,await body(req),t));
if(p.length===2&&m==='GET'){const[comments,activity,attachments]=await Promise.all([all('SELECT c.*,u.name author_name FROM comments c JOIN users u ON u.id=c.user_id WHERE task_id=? ORDER BY created_at',t.id),all('SELECT a.*,u.name author_name FROM activity a JOIN users u ON u.id=a.user_id WHERE task_id=? ORDER BY created_at',t.id),all('SELECT id,name,mime,size,created_at FROM attachments WHERE task_id=? ORDER BY created_at',t.id)]);return res({...t,comments,activity,attachments})}
if(p[2]==='comments'&&m==='POST'){await run('INSERT INTO comments (id,task_id,user_id,body,created_at) VALUES (?,?,?,?,?)',id(),t.id,u.id,str((await body(req)).body,'Комментарий'),now());return res({ok:true},201)}
if(p[2]==='status'&&m==='PATCH')return res(await changeTaskStatus({q,all,db,fail},u,t,(await body(req)).status));
if(p[2]==='approve'&&m==='POST'){manager(u);if(t.status!=='review')fail(409,'Задача должна быть на проверке');return res(await completeTask({q,all,db,fail},u,t))}
if(p[2]==='reject'&&m==='POST'){manager(u);if(t.status!=='review')fail(409,'Задача должна быть на проверке');const reason=str((await body(req)).reason,'Причина возврата');await changeTaskStatus({q,all,db,fail},u,t,'progress');await run("INSERT INTO comments (id,task_id,user_id,body,created_at) SELECT ?,?,?,?,? WHERE EXISTS (SELECT 1 FROM tasks WHERE id=? AND deleted_at IS NULL)",id(),t.id,u.id,'На доработку: '+reason,now(),t.id);return res({ok:true})}
if(p[2]==='attachments'&&m==='POST'){if(!env.BUCKET)fail(503,'Хранилище файлов недоступно');if(Number(req.headers.get('content-length')||0)>11*1024*1024)fail(413,'Максимальный размер файла — 10 МБ');const f=(await req.formData()).get('file');if(!(f instanceof File)||!f.size||f.size>10*1024*1024)fail(400,'Выберите файл размером до 10 МБ');const file=f as File,ext=file.name.split('.').pop()?.toLowerCase(),allowed:Record<string,string>={jpg:'image/jpeg',jpeg:'image/jpeg',png:'image/png',webp:'image/webp',pdf:'application/pdf',doc:'application/msword',docx:'application/vnd.openxmlformats-officedocument.wordprocessingml.document',txt:'text/plain'};if(!ext||!allowed[ext])fail(400,'Допустимы JPG, PNG, WebP, PDF, DOC, DOCX и TXT');const bytes=await file.arrayBuffer(),h=new Uint8Array(bytes).slice(0,12),sig=String.fromCharCode(...h);if((ext==='pdf'&&!sig.startsWith('%PDF-'))||(ext==='png'&&!(h[0]===137&&h[1]===80&&h[2]===78&&h[3]===71))||(['jpg','jpeg'].includes(ext)&&!(h[0]===255&&h[1]===216))||(ext==='webp'&&!(sig.startsWith('RIFF')&&sig.slice(8)==='WEBP'))||(ext==='docx'&&!(h[0]===80&&h[1]===75))||(ext==='doc'&&!(h[0]===208&&h[1]===207&&h[2]===17&&h[3]===224)))fail(400,'Содержимое не соответствует типу файла');const aid=id(),key=u.company_id+'/'+t.id+'/'+aid;await env.BUCKET!.put(key,bytes,{httpMetadata:{contentType:allowed[ext!]}});try{await run('INSERT INTO attachments (id,task_id,user_id,name,mime,size,object_key,created_at) VALUES (?,?,?,?,?,?,?,?)',aid,t.id,u.id,file.name.slice(0,200),allowed[ext!],file.size,key,now())}catch(e){await env.BUCKET!.delete(key);throw e}return res({ok:true},201)}}
if(p[0]==='files'&&m==='GET'){const a=await one('SELECT * FROM attachments WHERE id=?',p[1]);if(!a)fail(404,'Файл не найден');await taskAccess(u,a!.task_id);const obj=await env.BUCKET?.get(a!.object_key);if(!obj)fail(404,'Файл недоступен');return new Response(obj!.body,{headers:{'Content-Type':a!.mime,'Content-Disposition':`attachment; filename="download"; filename*=UTF-8''${encodeURIComponent(a!.name)}`,'X-Content-Type-Options':'nosniff','Cache-Control':'private, no-store'}})}
if(p[0]==='users'){if(m==='GET')return res((await state(u)).users);admin(u);if(m==='POST'){const b=await body(req),uid=id();await run('INSERT INTO users (id,company_id,name,email,password,role,position,department,phone,created_at) VALUES (?,?,?,?,?,?,?,?,?,?)',uid,u.company_id,str(b.name,'Имя',120),email(b.email),await hash(password(b.password)),['employee','manager','admin'].includes(b.role)?b.role:'employee',String(b.position||'').slice(0,100),String(b.department||'').slice(0,100),String(b.phone||'').slice(0,40),now());return res({id:uid},201)}const target=await one('SELECT * FROM users WHERE id=? AND company_id=?',p[1],u.company_id);if(!target)fail(404,'Пользователь не найден');if(target!.id===u.id)fail(400,'Измените собственные данные в профиле');if(m==='DELETE'){const refs=await one('SELECT (SELECT COUNT(*) FROM tasks WHERE assignee_id=? OR author_id=? OR id IN (SELECT task_id FROM task_assignees WHERE user_id=?))+(SELECT COUNT(*) FROM ledger WHERE user_id=? OR approved_by=?)+(SELECT COUNT(*) FROM claims WHERE user_id=?)+(SELECT COUNT(*) FROM comments WHERE user_id=?)+(SELECT COUNT(*) FROM activity WHERE user_id=?)+(SELECT COUNT(*) FROM attachments WHERE user_id=?) n',...Array(9).fill(target!.id));if(refs!.n)fail(409,'У сотрудника есть история. Используйте блокировку для сохранения данных.');await db().batch([q('DELETE FROM notifications WHERE user_id=?',target!.id),q('DELETE FROM sessions WHERE user_id=?',target!.id),q('DELETE FROM resets WHERE user_id=?',target!.id),q('DELETE FROM users WHERE id=?',target!.id)]);return res({ok:true})}if(m==='PATCH'){const b=await body(req),role=b.role??target!.role;if(!['employee','manager','admin'].includes(role))fail(400,'Недопустимая роль');await db().batch([q('UPDATE users SET name=?,email=?,phone=?,position=?,department=?,role=?,active=?,password=? WHERE id=? AND company_id=?',str(b.name??target!.name,'Имя',120),email(b.email??target!.email),String(b.phone??target!.phone).slice(0,40),String(b.position??target!.position).slice(0,100),String(b.department??target!.department).slice(0,100),role,b.active===undefined?target!.active:(b.active?1:0),b.password?await hash(password(b.password)):target!.password,target!.id,u.company_id),q('DELETE FROM sessions WHERE user_id=?',target!.id)]);return res({ok:true})}}
if(p[0]==='profile'&&m==='PATCH'){const b=await body(req);if(b.new_password&&await hash(String(b.current_password||''),u.password.split(':')[0])!==u.password)fail(400,'Текущий пароль неверен');await run('UPDATE users SET name=?,phone=? WHERE id=?',str(b.name,'Имя',120),String(b.phone||'').slice(0,40),u.id);if(b.new_password){await db().batch([q('UPDATE users SET password=? WHERE id=?',await hash(password(b.new_password)),u.id),q('DELETE FROM sessions WHERE user_id=?',u.id)]);return res({ok:true},200,{'Set-Cookie':await cookie(u,req)})}return res({ok:true})}
if(p[0]==='points'){if(m==='GET')return res((await state(u)).ledger);if(p[1]==='bonus'&&m==='POST'){manager(u);const b=await body(req),target=await one("SELECT id FROM users WHERE id=? AND company_id=? AND active=1 AND role='employee'",b.user_id,u.company_id);if(!target)fail(400,'Выберите сотрудника');const c=await one('SELECT settings FROM companies WHERE id=?',u.company_id);if(!JSON.parse(c!.settings).points)fail(400,'Система баллов отключена');const amount=num(b.amount,'Баллы'),reason=str(b.reason,'Причина',500);await db().batch([q('INSERT INTO ledger (id,company_id,user_id,amount,reason,approved_by,created_at) VALUES (?,?,?,?,?,?,?)',id(),u.company_id,target!.id,amount,reason,u.id,now()),note(u.company_id,target!.id,`Начислен бонус: ${amount} баллов. ${reason}`)]);return res({ok:true})}}
if(p[0]==='notifications'&&m==='PATCH'){await run('UPDATE notifications SET read=1 WHERE user_id=?'+(p[1]?' AND id=?':''),...[u.id,...(p[1]?[p[1]]:[])]);return res({ok:true})}
if(p[0]==='settings'&&m==='PATCH'){admin(u);const b=await body(req);await run('UPDATE companies SET name=?,settings=? WHERE id=?',str(b.name,'Компания',120),JSON.stringify({points:!!b.points,rating:!!b.rating,rewards:!!b.rewards}),u.company_id);return res({ok:true})}
if(p[0]==='rewards'){if(m==='GET')return res((await state(u)).rewards);if(p.length===1&&m==='POST'){manager(u);const b=await body(req);await run('INSERT INTO rewards (id,company_id,title,description,cost,stock,icon) VALUES (?,?,?,?,?,?,?)',id(),u.company_id,str(b.title,'Название',120),str(b.description,'Описание',1000),num(b.cost,'Стоимость'),num(b.stock,'Количество',1,10000),['gift','sun','coffee','clock'].includes(b.icon)?b.icon:'gift');return res({ok:true},201)}const r=await one('SELECT * FROM rewards WHERE id=? AND company_id=?',p[1],u.company_id);if(!r)fail(404,'Награда не найдена');if(m==='PATCH'){manager(u);await run('UPDATE rewards SET active=? WHERE id=?',(await body(req)).active?1:0,r!.id);return res({ok:true})}if(p[2]==='claim'&&m==='POST'){if(u.role!=='employee')fail(403,'Награды доступны сотрудникам');const c=await one('SELECT settings FROM companies WHERE id=?',u.company_id),s=JSON.parse(c!.settings);if(!s.rewards||!s.points)fail(400,'Каталог наград отключён');const result=await run("INSERT INTO claims (id,reward_id,user_id,cost,created_at) SELECT ?,?,?,?,? WHERE EXISTS (SELECT 1 FROM rewards WHERE id=? AND active=1 AND stock>(SELECT COUNT(*) FROM claims WHERE reward_id=? AND status IN ('pending','confirmed'))) AND COALESCE((SELECT SUM(amount) FROM ledger WHERE user_id=?),0)-COALESCE((SELECT SUM(cost) FROM claims WHERE user_id=? AND status='pending'),0)>=? AND NOT EXISTS (SELECT 1 FROM claims WHERE reward_id=? AND user_id=? AND status='pending')",id(),r!.id,u.id,r!.cost,now(),r!.id,r!.id,u.id,u.id,r!.cost,r!.id,u.id);if(!result.meta.changes)fail(409,'Недостаточно доступных баллов, награда закончилась или заявка уже отправлена');const ns=await managers(u.company_id,u.name+' запросил(а) награду «'+r!.title+'»');if(ns.length)await db().batch(ns);return res({ok:true},201)}}
if(p[0]==='claims'&&m==='POST'){manager(u);const c=await one('SELECT c.*,r.title FROM claims c JOIN rewards r ON r.id=c.reward_id WHERE c.id=? AND r.company_id=?',p[1],u.company_id);if(!c||c.status!=='pending')fail(409,'Заявка недоступна');if(p[2]==='reject'){await db().batch([q("UPDATE claims SET status='rejected' WHERE id=? AND status='pending'",c!.id),note(u.company_id,c!.user_id,'Заявка на награду «'+c!.title+'» отклонена')]);return res({ok:true})}if(p[2]==='approve'){await db().batch([q("UPDATE claims SET status='confirmed',confirmed_at=? WHERE id=? AND status='pending' AND COALESCE((SELECT SUM(amount) FROM ledger WHERE user_id=?),0)>=cost",now(),c!.id,c!.user_id),q("INSERT OR IGNORE INTO ledger (id,company_id,user_id,amount,reason,reference,approved_by,created_at) SELECT ?,?,?,?,?,?,?,? WHERE EXISTS (SELECT 1 FROM claims WHERE id=? AND status='confirmed')",id(),u.company_id,c!.user_id,-c!.cost,'Награда «'+c!.title+'»','claim:'+c!.id,u.id,now(),c!.id)]);if((await one('SELECT status FROM claims WHERE id=?',c!.id))!.status!=='confirmed')fail(409,'Недостаточно баллов');await db().batch([note(u.company_id,c!.user_id,'Подтверждена награда «'+c!.title+'»',null,'claim-approved:'+c!.id)]);return res({ok:true})}}
fail(404,'Метод API не найден');}catch(e){if(e instanceof ApiError)return res({error:e.message},e.status);console.error('StaffTrack API:',String(e));if(String(e).includes('UNIQUE constraint failed: users.email'))return res({error:'Этот email уже занят'},409);return res({error:'Не удалось выполнить операцию. Попробуйте снова.'},500)}}
