// Intentionally empty by default.
// Add Drizzle tables here when the site actually needs a database.
// See examples/d1/db/schema.ts for an opt-in example.
import { sqliteTable, text, integer, index, primaryKey } from 'drizzle-orm/sqlite-core';
export const companies=sqliteTable('companies',{id:text().primaryKey(),name:text().notNull(),createdAt:text('created_at').notNull(),settings:text().notNull().default('{"points":true,"rating":true,"rewards":true}')});
export const users=sqliteTable('users',{id:text().primaryKey(),companyId:text('company_id').notNull().references(()=>companies.id),name:text().notNull(),email:text().notNull().unique(),password:text().notNull(),role:text().notNull(),position:text().notNull().default(''),department:text().notNull().default(''),phone:text().notNull().default(''),active:integer().notNull().default(1),createdAt:text('created_at').notNull()},t=>[index('users_company').on(t.companyId)]);
export const sessions=sqliteTable('sessions',{token:text().primaryKey(),userId:text('user_id').notNull().references(()=>users.id),expires:text().notNull()});
export const tasks=sqliteTable('tasks',{id:text().primaryKey(),companyId:text('company_id').notNull().references(()=>companies.id),title:text().notNull(),description:text().notNull(),assigneeId:text('assignee_id').notNull().references(()=>users.id),authorId:text('author_id').notNull().references(()=>users.id),deadline:text().notNull(),priority:text().notNull(),status:text().notNull().default('new'),points:integer().notNull(),createdAt:text('created_at').notNull(),startedAt:text('started_at'),completedAt:text('completed_at'),approvedAt:text('approved_at'),deletedAt:text('deleted_at')},t=>[index('tasks_company_assignee').on(t.companyId,t.assigneeId)]);
export const comments=sqliteTable('comments',{id:text().primaryKey(),taskId:text('task_id').notNull().references(()=>tasks.id),userId:text('user_id').notNull().references(()=>users.id),body:text().notNull(),createdAt:text('created_at').notNull()},t=>[index('comments_task').on(t.taskId)]);
export const taskAssignees=sqliteTable('task_assignees',{taskId:text('task_id').notNull().references(()=>tasks.id),userId:text('user_id').notNull().references(()=>users.id)},t=>[primaryKey({columns:[t.taskId,t.userId]}),index('task_assignees_user').on(t.userId)]);
export const activity=sqliteTable('activity',{id:text().primaryKey(),taskId:text('task_id').notNull().references(()=>tasks.id),userId:text('user_id').notNull().references(()=>users.id),body:text().notNull(),createdAt:text('created_at').notNull()},t=>[index('activity_task').on(t.taskId)]);
export const ledger=sqliteTable('ledger',{id:text().primaryKey(),companyId:text('company_id').notNull().references(()=>companies.id),userId:text('user_id').notNull().references(()=>users.id),amount:integer().notNull(),reason:text().notNull(),reference:text().unique(),approvedBy:text('approved_by').notNull().references(()=>users.id),createdAt:text('created_at').notNull()},t=>[index('ledger_company_user_date').on(t.companyId,t.userId,t.createdAt)]);
export const notifications=sqliteTable('notifications',{id:text().primaryKey(),companyId:text('company_id').notNull(),userId:text('user_id').notNull().references(()=>users.id),title:text().notNull(),taskId:text('task_id'),read:integer().notNull().default(0),createdAt:text('created_at').notNull()},t=>[index('notifications_user').on(t.userId)]);
export const rewards=sqliteTable('rewards',{id:text().primaryKey(),companyId:text('company_id').notNull().references(()=>companies.id),title:text().notNull(),description:text().notNull(),cost:integer().notNull(),stock:integer().notNull(),active:integer().notNull().default(1),icon:text().notNull().default('gift')});
export const claims=sqliteTable('claims',{id:text().primaryKey(),rewardId:text('reward_id').notNull().references(()=>rewards.id),userId:text('user_id').notNull().references(()=>users.id),cost:integer().notNull(),status:text().notNull().default('pending'),createdAt:text('created_at').notNull(),confirmedAt:text('confirmed_at')},t=>[index('claims_user_status').on(t.userId,t.status)]);
export const attachments=sqliteTable('attachments',{id:text().primaryKey(),taskId:text('task_id').notNull().references(()=>tasks.id),userId:text('user_id').notNull().references(()=>users.id),name:text().notNull(),mime:text().notNull(),size:integer().notNull(),objectKey:text('object_key').notNull(),createdAt:text('created_at').notNull()},t=>[index('attachments_task').on(t.taskId)]);
export const resets=sqliteTable('resets',{token:text().primaryKey(),userId:text('user_id').notNull().references(()=>users.id),expires:text().notNull()});
export const attempts=sqliteTable('attempts',{key:text().primaryKey(),count:integer().notNull().default(0),expires:text().notNull()});
